import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Link from "next/link";
import Image from "next/image";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ChevronDown, Home, LogOut, Settings, User } from "lucide-react";
import { ModeToggler } from "@/components/ModeToggler";

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={cairo.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header>
            <div className="bg-background border-b">
              <ul className="container flex justify-between gap-4 items-center py-8 ">
                <li>
                  <Link href="/" className="flex items-center gap-1 font-bold text-lg uppercase">
                    <Image src="/assets/Zeronet_logo.png" alt="E-Commerce" width="60" height="60" priority />
                    متجري
                  </Link>
                </li>
                <li>
                  <ul className="flex">
                    <li className="font-semibold h-14 pe-6 border-e flex items-center justify-center">English</li>
                    <li className="flex items-center h-14 px-6 border-e justify-center flex-col">
                      <span className="text-sm text-muted-foreground">مرحبًا يا عبدالرحمن،</span>

                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <button className="flex gap-1 items-center mt-1 py-1 px-2 focus">
                            تفاصيل حسابك <ChevronDown className="w-4" />
                          </button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent>
                          <DropdownMenuGroup>
                            <DropdownMenuItem>
                              <Link href="/profile" className="flex rtl:flex-row-reverse gap-2 items-center w-full">
                                <User className="h-4 w-4" />
                                <span>الملف الشخصي</span>
                              </Link>
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              <Link href="/profile" className="flex rtl:flex-row-reverse gap-2 items-center w-full">
                                <Settings className="h-4 w-4" />
                                <span>الإعدادات</span>
                              </Link>
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              <Link href="/dashboard" className="flex rtl:flex-row-reverse gap-2 items-center w-full">
                                <Home className="h-4 w-4" />
                                <span>الصفحة الرئيسية</span>
                              </Link>
                            </DropdownMenuItem>
                          </DropdownMenuGroup>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem>
                            <button className="flex rtl:flex-row-reverse gap-2 items-center w-full">
                              <LogOut className="h-4 w-4" />
                              <span>تسجيل الخروج</span>
                            </button>
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </li>
                    <li className="font-semibold h-14 ps-6 flex items-center justify-center">
                      <ModeToggler />
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
            <div className="bg-background border-b">{/* <Navbar /> */}</div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
